# Generated by Django 3.2.6 on 2021-11-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotipo',
            name='pordefecto',
            field=models.BooleanField(default=False, verbose_name='Por Defecto'),
        ),
    ]
