# Generated by Django 3.2.6 on 2021-11-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0002_documentotipo_pordefecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='presiglas',
            field=models.CharField(default='', max_length=50),
        ),
    ]
