# Generated by Django 3.2.6 on 2021-11-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0003_documento_presiglas'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotipo',
            name='autorizacomision',
            field=models.BooleanField(default=False, verbose_name='Autoriza Comisión'),
        ),
    ]
