# Generated by Django 3.2.9 on 2021-12-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0006_auto_20211203_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='diasatencion',
            field=models.IntegerField(default=0, verbose_name='Días de Atención'),
        ),
    ]
