# Generated by Django 3.2.9 on 2021-12-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0007_alter_destino_diasatencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotipo',
            name='nombrecorto',
            field=models.CharField(default='', max_length=15, verbose_name='Nombre Corto'),
        ),
    ]
