# Generated by Django 3.2.9 on 2021-12-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0010_documento_personajuridicatipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='personajuridicatipo',
            field=models.CharField(blank=True, choices=[('R', 'RUC'), ('O', 'OTRO')], max_length=1, null=True, verbose_name='Tipo Persona Jurídica'),
        ),
    ]
