# Generated by Django 3.2.9 on 2022-01-10 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0018_periodotrabajo_apoyoarea'),
        ('tramite', '0015_documentoreferencia_expedienteemi'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expediente',
            unique_together={('dependencia', 'anio', 'numero')},
        ),
    ]
