# Generated by Django 3.2.9 on 2022-01-11 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0016_alter_expediente_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='tipodestinatario',
            field=models.CharField(choices=[('UO', 'Unidad Organizacional'), ('PJ', 'Persona Jurídica'), ('CI', 'Ciudadano')], max_length=2),
        ),
        migrations.AlterField(
            model_name='documento',
            name='ultimoestado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentoestados', to='tramite.documentoestado'),
        ),
    ]
