# Generated by Django 3.2.9 on 2022-01-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0017_auto_20220110_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='estadoemitido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentoemitido', to='tramite.documentoestado'),
        ),
    ]
