# Generated by Django 3.2.9 on 2022-01-13 22:34

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizacion', '0020_alter_periodotrabajo_emiteexterno'),
        ('inicio', '0009_persona_ultimocargo'),
        ('tramite', '0018_documento_estadoemitido'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalNumeracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('numero', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numeracionpersonal', to='organizacion.area')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numeraciones', to='inicio.persona')),
            ],
            options={
                'verbose_name': 'Numeración Personal',
                'verbose_name_plural': 'Numeraciones Personales',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
