# Generated by Django 3.2.9 on 2022-01-13 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0020_alter_periodotrabajo_emiteexterno'),
        ('tramite', '0019_personalnumeracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalnumeracion',
            name='area',
        ),
        migrations.AddField(
            model_name='personalnumeracion',
            name='documentotipoarea',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='numeracionpersonal', to='organizacion.documentotipoarea'),
            preserve_default=False,
        ),
    ]
