# Generated by Django 3.2.9 on 2022-01-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0020_auto_20220113_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivoexterno',
            field=models.URLField(blank=True, null=True, verbose_name='Archivo Externo'),
        ),
    ]
