# Generated by Django 3.2.9 on 2022-01-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0021_documento_archivoexterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='mesapartesmodoenvio',
            field=models.IntegerField(choices=[('0', 'Ninguno'), ('1', 'Imprimir los documentos y/o anexos; y entregarlos a Mesa de Partes.')], default=0),
        ),
    ]
