# Generated by Django 3.2.9 on 2022-01-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0022_alter_destino_mesapartesmodoenvio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribuidor',
            name='nombre',
        ),
    ]
