# Generated by Django 3.2.9 on 2022-02-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0023_remove_distribuidor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinoestado',
            name='observacion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
