# Generated by Django 3.2.9 on 2022-02-22 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0013_cargo_esapoyo'),
        ('tramite', '0026_alter_destinoestado_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargoexterno',
            name='modo',
        ),
        migrations.RemoveField(
            model_name='cargoexterno',
            name='mododistribucion',
        ),
        migrations.RemoveField(
            model_name='cargoexterno',
            name='tipo',
        ),
        migrations.AddField(
            model_name='destinoestadomensajeria',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargointernodetalle',
            name='cargointerno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listadestinos', to='tramite.cargointerno'),
        ),
        migrations.AlterField(
            model_name='cargointernodetalle',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargosinternos', to='tramite.destino'),
        ),
        migrations.AlterField(
            model_name='destinoestadomensajeria',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('RA', 'Recibido Automático'), ('RM', 'Recibido Manual'), ('DA', 'Devuelto Automático'), ('DM', 'Devuelto Manual'), ('EN', 'Enviado'), ('FI', 'Finalizado'), ('FD', 'Finalizado Directo')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pdistribuidores', to='inicio.persona'),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='personajuridica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pjdistribuidores', to='inicio.personajuridica', verbose_name=' Persona Jurídica'),
        ),
    ]
