# Generated by Django 3.2.9 on 2022-02-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0027_auto_20220222_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinoestadomensajeria',
            name='observacion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
