# Generated by Django 3.2.9 on 2022-03-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0028_alter_destinoestadomensajeria_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargoexterno',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='cargoexternodetalle',
            name='comentario',
        ),
        migrations.AddField(
            model_name='cargoexterno',
            name='cargofecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Cargo'),
        ),
        migrations.AddField(
            model_name='cargoexterno',
            name='cargoobservacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación del Cargo'),
        ),
        migrations.AddField(
            model_name='cargoexterno',
            name='cargopdf',
            field=models.BinaryField(blank=True, max_length='max', null=True, verbose_name='Cargo en PDF'),
        ),
        migrations.AddField(
            model_name='cargoexterno',
            name='nota',
            field=models.TextField(blank=True, null=True, verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='cargoexternodetalle',
            name='cargocomentario',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Comentario del Cargo'),
        ),
    ]
