# Generated by Django 3.2.9 on 2022-03-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0026_auto_20220127_1823'),
        ('tramite', '0030_auto_20220302_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargoexterno',
            old_name='emisor',
            new_name='emisortrabajador',
        ),
        migrations.RemoveField(
            model_name='cargoexterno',
            name='dependencia',
        ),
        migrations.AddField(
            model_name='cargoexterno',
            name='emisorarearindente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizacion.area'),
        ),
    ]
