# Generated by Django 3.2.9 on 2022-03-03 15:32

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tramite', '0031_auto_20220302_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoexternodetalle',
            name='cargoexterno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinos', to='tramite.cargoexterno', verbose_name='Cargo Externo'),
        ),
        migrations.AlterField(
            model_name='destinoestadomensajeria',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('RA', 'Recibido Automático'), ('RM', 'Recibido Manual'), ('DA', 'Devuelto Automático'), ('DM', 'Devuelto Manual'), ('GN', 'Generado'), ('EN', 'Enviado'), ('FI', 'Finalizado'), ('FD', 'Finalizado Directo'), ('RN', 'Recibido No Entregado'), ('AR', 'Archivado')], default='PE', max_length=2),
        ),
        migrations.CreateModel(
            name='CargoExternoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.CharField(choices=[('GN', 'Generado'), ('EN', 'Enviado'), ('FI', 'Finalizado')], max_length=2)),
                ('observacion', models.TextField(blank=True, max_length=500, null=True)),
                ('cargoexterno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados', to='tramite.cargoexterno')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cargo Externo Estado',
                'verbose_name_plural': 'Cargo Externo Estados',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='cargoexterno',
            name='ultimoestado',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='ultimoestado', to='tramite.cargoexternoestado'),
            preserve_default=False,
        ),
    ]
