# Generated by Django 4.0.3 on 2022-03-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0036_alter_cargoexternoestado_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentopdfrevisiones',
            name='impreso',
            field=models.BooleanField(default=False, verbose_name='Se ha impreso'),
        ),
    ]
