# Generated by Django 4.0.3 on 2022-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0037_documentopdfrevisiones_impreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='mesapartesmodoenvio',
            field=models.IntegerField(choices=[('0', 'Ninguno'), ('1', 'Imprimir los documentos y/o anexos; y entregarlos a Mensajería.')], default=0),
        ),
    ]
