# Generated by Django 4.0.3 on 2022-03-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0040_documentotipo_forma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentotipo',
            name='forma',
        ),
        migrations.AddField(
            model_name='documentotipo',
            name='tieneforma',
            field=models.BooleanField(default=False, verbose_name='Tiene Forma'),
        ),
    ]
