# Generated by Django 4.0.3 on 2022-03-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0042_documento_forma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinoestadomensajeria',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('RA', 'Recibido Automático'), ('RM', 'Recibido Manual'), ('DA', 'Devuelto Automático'), ('DM', 'Devuelto Manual'), ('GN', 'Generado'), ('EN', 'Enviado'), ('FI', 'Finalizado'), ('FD', 'Finalizado Directo'), ('NE', 'No Entregado'), ('AR', 'Archivado'), ('EC', 'Enviado por Correo'), ('ED', 'Entrega Directa')], default='PE', max_length=2),
        ),
    ]
