# Generated by Django 4.0.3 on 2022-03-23 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0015_auto_20220306_2113'),
        ('tramite', '0043_alter_destinoestadomensajeria_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoexternodetalle',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cargoexternodetalle',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='cargoexternodetalle',
            name='referencia',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Referencia de la Dirección'),
        ),
        migrations.AddField(
            model_name='cargoexternodetalle',
            name='ubigeo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cet_ubigeo', to='inicio.distrito'),
        ),
    ]
