# Generated by Django 4.0.3 on 2022-03-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0044_cargoexternodetalle_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoexternodetalle',
            name='detalle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalle'),
        ),
    ]
