# Generated by Django 4.0.3 on 2022-03-24 20:56

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tramite', '0045_cargoexternodetalle_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='mesapartesmodoenvio',
            field=models.IntegerField(choices=[('0', 'Ninguno'), ('1', 'Imprimir los documentos y/o anexos; y entregarlos a Mensajería.')], default=0, verbose_name='Modo de Envío a Mesa de Partes'),
        ),
        migrations.CreateModel(
            name='MensajeriaModoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('codigo', models.CharField(max_length=2, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modo de Entrega',
                'verbose_name_plural': 'Modos de Entrega',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
