# Generated by Django 4.0.3 on 2022-03-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0046_alter_destino_mesapartesmodoenvio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeriamodoentrega',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='mensajeriamodoentrega',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='mensajeriamodoentrega',
            name='icono',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Icono'),
        ),
        migrations.AddField(
            model_name='mensajeriamodoentrega',
            name='orden',
            field=models.IntegerField(default=100, verbose_name='Orden'),
        ),
    ]
