# Generated by Django 4.0.3 on 2022-03-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0047_mensajeriamodoentrega_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeriamodoentrega',
            name='color',
            field=models.CharField(default=None, max_length=30, verbose_name='Color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensajeriamodoentrega',
            name='icono',
            field=models.CharField(default=None, max_length=100, verbose_name='Icono'),
            preserve_default=False,
        ),
    ]
