# Generated by Django 4.0.3 on 2022-03-24 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0048_alter_mensajeriamodoentrega_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='mensajeriamodoentrega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tramite.mensajeriamodoentrega', verbose_name='Modo de Entrega'),
            preserve_default=False,
        ),
    ]
