# Generated by Django 4.0.3 on 2022-03-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0050_mensajeriamodoentrega_mensajeriaestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='mesapartesmodoenvio',
            field=models.IntegerField(choices=[(0, 'Ninguno'), (1, 'Imprimir los documentos y/o anexos; y entregarlos a Mensajería.')], default=0, verbose_name='Modo de Envío a Mesa de Partes'),
        ),
    ]
