# Generated by Django 4.0.3 on 2022-03-30 19:43

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizacion', '0028_area_mensajeriahoramaxima'),
        ('tramite', '0051_alter_destino_mesapartesmodoenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPDFTokenLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('direccionip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('nombreequipo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de Equipo')),
                ('es_mobile', models.BooleanField(default=False, verbose_name='Es Mobile')),
                ('es_tablet', models.BooleanField(default=False, verbose_name='Es Tablet')),
                ('es_touch', models.BooleanField(default=False, verbose_name='Es Touch')),
                ('es_pc', models.BooleanField(default=False, verbose_name='Es PC')),
                ('es_bot', models.BooleanField(default=False, verbose_name='Es BOT')),
                ('navegador_familia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Navegador Familia')),
                ('navegador_version', models.CharField(blank=True, max_length=200, null=True, verbose_name='Navegador Versión')),
                ('so_familia', models.CharField(blank=True, max_length=200, null=True, verbose_name='S.O. Familia')),
                ('so_version', models.CharField(blank=True, max_length=200, null=True, verbose_name='S.O. Versión')),
                ('device_familia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Device Familia')),
                ('token', models.CharField(max_length=5, verbose_name='Token Código')),
                ('tokencorreo', models.EmailField(max_length=254, verbose_name='Token Correo')),
                ('tokenvalido', models.DateTimeField(verbose_name='Token Válidación Usar')),
                ('tokencorreoenvio', models.DateTimeField(blank=True, null=True, verbose_name='Token Envío')),
                ('tokenusado', models.DateTimeField(blank=True, null=True, verbose_name='Token Uso')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documentopdf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='tramite.documentopdf', verbose_name='Documento PDF')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tokensolicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacion.periodotrabajo', verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Lectura de Token',
                'verbose_name_plural': 'Lecturas de Token',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
