# Generated by Django 4.0.3 on 2022-03-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0052_documentopdftokenlectura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='confidencialclave',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='confidencialencriptado',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='confidencialenviado',
        ),
        migrations.AlterField(
            model_name='documento',
            name='origentipo',
            field=models.CharField(choices=[('O', 'EMISIÓN DE OFICINA'), ('P', 'EMISIÓN PROFESIONAL'), ('F', 'MESA DE PARTES FÍSICA'), ('V', 'MESA DE PARTES VIRTUAL'), ('I', 'INTEROPERABILIDAD'), ('C', 'COURRIER'), ('A', 'ACCESO A LA INFORMACIÓN')], max_length=1),
        ),
        migrations.AlterField(
            model_name='documentopdftokenlectura',
            name='tokenvalido',
            field=models.DateTimeField(auto_now=True, verbose_name='Token Válidación Usar'),
        ),
    ]
