# Generated by Django 4.0.3 on 2022-04-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0053_remove_documento_confidencialclave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentopdftokenlectura',
            name='tokenvalido',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Token Válidación Usar'),
        ),
    ]
