# Generated by Django 4.0.3 on 2022-04-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0054_alter_documentopdftokenlectura_tokenvalido'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotipo',
            name='siglassinproyeccion',
            field=models.BooleanField(default=False, verbose_name='Siglas sin Proyección'),
        ),
    ]
