# Generated by Django 4.0.3 on 2022-04-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0055_documentotipo_siglassinproyeccion'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentoplantilla',
            index=models.Index(fields=['codigo'], name='tramite_doc_codigo_0aaadd_idx'),
        ),
    ]
