# Generated by Django 4.0.3 on 2022-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0056_documentoplantilla_tramite_doc_codigo_0aaadd_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='anexofirma',
            index=models.Index(fields=['codigouuid'], name='tramite_ane_codigou_71c0e8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofirma',
            index=models.Index(fields=['codigouuid'], name='tramite_doc_codigou_5891cc_idx'),
        ),
    ]
