# Generated by Django 4.0.3 on 2022-04-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0057_anexofirma_tramite_ane_codigou_71c0e8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='confidencial',
            field=models.BooleanField(default=False, verbose_name='Privado'),
        ),
    ]
