# Generated by Django 4.0.3 on 2022-05-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0060_anexorevisiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='entregafisica',
            field=models.TextField(blank=True, null=True, verbose_name='ENTREGA FÍSICA (Ejemplo: 01 Expediente, 03 CDs, 01 Expediente con 180 Folios, 01 Laptop, etc.)'),
        ),
    ]
