# Generated by Django 4.0.3 on 2022-06-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0061_alter_destino_entregafisica'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotipo',
            name='paraderivacion',
            field=models.BooleanField(default=False, verbose_name='Para Derivación'),
        ),
    ]
