# Generated by Django 4.0.5 on 2022-06-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0063_documento_anularemision'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoreferenciaorigen',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
