# Generated by Django 3.2.6 on 2021-11-12 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('codigo', models.CharField(default='', max_length=5)),
                ('orden', models.IntegerField(verbose_name='Orden')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('nombrecorto', models.CharField(max_length=50, verbose_name='Nombre Corto')),
                ('siglas', models.CharField(max_length=20, verbose_name='Siglas')),
                ('mesadepartes', models.BooleanField(default=False, verbose_name='Mesa de Partes')),
                ('paracomisiones', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('modificado', models.BooleanField(default=True)),
                ('esrindente', models.BooleanField(default=False, verbose_name='Es Rindente')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Web Site')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='AreaTipo',
            fields=[
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('paracomision', models.BooleanField(default=False)),
                ('icono', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Área',
                'verbose_name_plural': 'Tipos de Áreas',
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('orden', models.IntegerField(verbose_name='Orden')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('nombrecorto', models.CharField(max_length=50, verbose_name='Nombre Corto')),
                ('siglas', models.CharField(max_length=20, verbose_name='Siglas')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Página Web')),
                ('ruc', models.CharField(blank=True, max_length=11, null=True, verbose_name='RUC')),
                ('rucfirma', models.CharField(blank=True, max_length=11, null=True, verbose_name='Ruc para Firma')),
                ('titulodoc1', models.CharField(default='', max_length=200, verbose_name='Título Documento')),
                ('titulodoc2', models.CharField(default='', max_length=200, verbose_name='Sub Título Documento')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTipoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento por Área',
                'verbose_name_plural': 'Tipos de Documento por Área',
                'ordering': ['documentotipo__nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('iniciales', models.CharField(blank=True, max_length=10, null=True)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('poscargo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Pos Cargo')),
                ('permisotramite', models.CharField(choices=[('O', 'OPERADOR'), ('T', 'TRAMITADOR DOCUMENTAL')], max_length=1, verbose_name='Modo')),
                ('esapoyo', models.BooleanField(default=False, verbose_name='Es Apoyo')),
                ('esjefemodo', models.CharField(choices=[('NO', 'NO'), ('TI', 'TITULAR'), ('TE', 'TITULAR ENCARGADO')], default='NO', max_length=2, verbose_name='Es Jefe')),
                ('esjefe', models.BooleanField(default=False, verbose_name='Es Jefe')),
                ('tipo', models.CharField(choices=[('NN', 'Normal'), ('EN', 'Encargatura'), ('AP', 'Apoyo')], default='NN', max_length=2)),
                ('encargaturaplantilla', models.BinaryField(blank=True, max_length='max', null=True, verbose_name='Sustento Encargatura')),
                ('encargaturaplantillaanulacion', models.BinaryField(blank=True, max_length='max', null=True, verbose_name='Sustento Anulación')),
                ('modificado', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='organizacion.area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.cargo', verbose_name='Cargo')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Periodo de Trabajo',
                'verbose_name_plural': 'Periodos de Trabajo',
                'ordering': ['persona__apellidocompleto'],
            },
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('areaorigen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacion.area', verbose_name='Área Origen')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('periodotrabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyeccionareas', to='organizacion.periodotrabajo', verbose_name='Periodo de Trabajo')),
            ],
            options={
                'verbose_name': 'Proyección',
                'verbose_name_plural': 'Proyecciones',
                'ordering': ['areaorigen__nombre'],
            },
        ),
    ]
