# Generated by Django 3.2.6 on 2021-11-12 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        ('inicio', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tramite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodotrabajo',
            name='documentosustento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tramite.documento'),
        ),
        migrations.AddField(
            model_name='periodotrabajo',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodotrabajo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='inicio.persona'),
        ),
        migrations.AddField(
            model_name='documentotipoarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacion.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='documentotipoarea',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentotipoarea',
            name='documentotipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tramite.documentotipo', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='documentotipoarea',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijas', to='organizacion.dependencia', verbose_name='Padre'),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='ubigeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.distrito', verbose_name='Ubigeo'),
        ),
        migrations.AddField(
            model_name='areatipo',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='areatipo',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='areatipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacion.areatipo', verbose_name='Tipo de Área'),
        ),
        migrations.AddField(
            model_name='area',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacion.dependencia'),
        ),
        migrations.AddField(
            model_name='area',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inicio.distrito', verbose_name='Ubigeo'),
        ),
        migrations.AddField(
            model_name='area',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='jefeactual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jefearea', to='organizacion.periodotrabajo'),
        ),
        migrations.AddField(
            model_name='area',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subareas', to='organizacion.area'),
        ),
        migrations.AddField(
            model_name='area',
            name='rindentepadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rindenteoficinas', to='organizacion.area', verbose_name='Rindente Padre'),
        ),
    ]
