# Generated by Django 3.2.6 on 2021-11-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0005_alter_area_documentosustento'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='documentoautorizacion',
            field=models.BinaryField(blank=True, max_length='max', null=True, verbose_name='Documento Autorización'),
        ),
    ]
