# Generated by Django 3.2.6 on 2021-11-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0007_area_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='usaniveles',
            field=models.BooleanField(default=False, verbose_name='Usa Niveles'),
        ),
    ]
