# Generated by Django 3.2.6 on 2021-11-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0008_dependencia_usaniveles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='website',
            new_name='web',
        ),
    ]
