# Generated by Django 3.2.6 on 2021-11-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0009_rename_website_area_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='documentosustento',
        ),
    ]
