# Generated by Django 3.2.6 on 2021-11-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0011_periodotrabajo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodotrabajo',
            name='aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presidentesaprobados', to='organizacion.periodotrabajo'),
        ),
    ]
