# Generated by Django 3.2.6 on 2021-11-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0012_periodotrabajo_aprobador'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodotrabajo',
            name='aprobadorfecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación'),
        ),
    ]
