# Generated by Django 3.2.6 on 2021-12-03 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0013_periodotrabajo_aprobadorfecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Unidad Organizacional', 'verbose_name_plural': 'Unidades Organizacionales'},
        ),
        migrations.AlterModelOptions(
            name='areatipo',
            options={'verbose_name': 'Tipo de Unidad Organizacional', 'verbose_name_plural': 'Tipos de Unidades Organizacionales'},
        ),
        migrations.AlterModelOptions(
            name='documentotipoarea',
            options={'ordering': ['documentotipo__nombre'], 'verbose_name': 'Tipo de Documento por Unidad Organizacional', 'verbose_name_plural': 'Tipos de Documento por Unidad Organizacional'},
        ),
        migrations.AlterField(
            model_name='area',
            name='areatipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacion.areatipo', verbose_name='Tipo de Unidad Organizacional'),
        ),
        migrations.AlterField(
            model_name='documentotipoarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacion.area', verbose_name='Unidad Organizacional'),
        ),
        migrations.AlterField(
            model_name='proyeccion',
            name='areaorigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacion.area', verbose_name='Unidad Organizacional de Origen'),
        ),
    ]
