# Generated by Django 3.2.9 on 2021-12-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0014_auto_20211203_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodotrabajo',
            name='tipo',
            field=models.CharField(choices=[('NN', 'Normal'), ('EN', 'Encargatura de Funciones'), ('EP', 'Encargatura de Puesto'), ('AP', 'Apoyo')], default='NN', max_length=2),
        ),
    ]
