# Generated by Django 3.2.9 on 2021-12-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0017_area_comisiondirecta'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodotrabajo',
            name='apoyoarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizacion.area', verbose_name='Área de Apoyo'),
        ),
    ]
