# Generated by Django 3.2.9 on 2022-01-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0018_periodotrabajo_apoyoarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodotrabajo',
            name='emiteexterno',
            field=models.BooleanField(default=False),
        ),
    ]
