# Generated by Django 3.2.9 on 2022-01-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0020_alter_periodotrabajo_emiteexterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='estado',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Estado'),
        ),
    ]
