# Generated by Django 3.2.9 on 2022-01-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0021_dependencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotipoarea',
            name='correlativo',
            field=models.IntegerField(default=0, verbose_name='Correlativo'),
        ),
    ]
