# Generated by Django 3.2.9 on 2022-01-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0022_alter_destino_mesapartesmodoenvio'),
        ('organizacion', '0023_periodotrabajo_seguimientocompleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='mensajeria',
            field=models.BooleanField(default=False, verbose_name='Realiza Mensajería'),
        ),
        migrations.AddField(
            model_name='area',
            name='mensajeriaambito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tramite.ambitomensajeria', verbose_name='Ambito de Mensajería'),
        ),
        migrations.AddField(
            model_name='area',
            name='mensajeriadistritos',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Distritos de Mensajería'),
        ),
    ]
