# Generated by Django 3.2.9 on 2022-01-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0024_auto_20220127_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodotrabajo',
            name='esmensajero',
            field=models.BooleanField(default=False, verbose_name='Mensajero'),
        ),
    ]
