# Generated by Django 3.2.9 on 2022-01-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0025_periodotrabajo_esmensajero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='mensajeria',
            field=models.BooleanField(default=False, verbose_name='Mensajería'),
        ),
        migrations.AlterField(
            model_name='periodotrabajo',
            name='esjefemodo',
            field=models.CharField(choices=[('NO', 'NO'), ('TI', 'TITULAR'), ('TE', 'TITULAR ENCARGADO'), ('TS', 'SEGUNDO TITULAR'), ('TT', 'TERCER TITULAR')], default='NO', max_length=2, verbose_name='Es Jefe'),
        ),
    ]
