# Generated by Django 3.2.9 on 2022-03-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0026_auto_20220127_1823'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['nombre'], name='organizacio_nombre_9a5026_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['siglas'], name='organizacio_siglas_0bbcb5_idx'),
        ),
        migrations.AddIndex(
            model_name='areatipo',
            index=models.Index(fields=['nombre'], name='organizacio_nombre_a1e496_idx'),
        ),
        migrations.AddIndex(
            model_name='dependencia',
            index=models.Index(fields=['nombre'], name='organizacio_nombre_8292f2_idx'),
        ),
    ]
