# Generated by Django 4.0.3 on 2022-03-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0027_auto_20220306_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='mensajeriahoramaxima',
            field=models.TimeField(blank=True, null=True, verbose_name='Mensajería Hora Máxima'),
        ),
    ]
