# Generated by Django 4.0.3 on 2022-04-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0028_area_mensajeriahoramaxima'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='firmamargensuperior',
            field=models.IntegerField(default=0, verbose_name='Margen Superior de la Firma'),
        ),
    ]
