# Generated by Django 4.0.3 on 2022-05-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0029_area_firmamargensuperior'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodotrabajo',
            name='apoyoforma',
            field=models.CharField(choices=[('A', 'Administrativo'), ('T', 'Técnico')], default='A', max_length=1, verbose_name='Forma de Apoyo'),
        ),
    ]
