# Generated by Django 4.0.5 on 2022-06-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0030_periodotrabajo_apoyoforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='sello_cargo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Sello de Cargo'),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='sello_firma',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Sello de Firma'),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='sello_firma_adicional',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Sello de Firma Adicional'),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='sello_firmagrc',
            field=models.BooleanField(default=False, verbose_name='Sello interno del Firmador'),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='sello_vistobueno',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Sello de VB'),
        ),
    ]
