# Generated by Django 4.0.5 on 2022-06-27 17:46

import apps.organizacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0031_dependencia_sello_cargo_dependencia_sello_firma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='sello_cargo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.organizacion.models.Dependencia.selloPath, verbose_name='Sello de Cargo'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='sello_firma',
            field=models.ImageField(blank=True, null=True, upload_to=apps.organizacion.models.Dependencia.selloPath, verbose_name='Sello de Firma'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='sello_firma_adicional',
            field=models.ImageField(blank=True, null=True, upload_to=apps.organizacion.models.Dependencia.selloPath, verbose_name='Sello de Firma Adicional'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='sello_vistobueno',
            field=models.ImageField(blank=True, null=True, upload_to=apps.organizacion.models.Dependencia.selloPath, verbose_name='Sello de VB'),
        ),
    ]
