# Generated by Django 4.0.5 on 2022-06-28 03:16

import apps.organizacion.models
import django.core.validators
from django.db import migrations, models
import modulos.utiles.clases.varios


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0032_alter_dependencia_sello_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='sello_cargo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.organizacion.models.Dependencia.selloPath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), modulos.utiles.clases.varios.FileDimensionValidator(200, 68)], verbose_name='Sello de Cargo'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='sello_firma',
            field=models.ImageField(blank=True, help_text=['El tamaño debe de ser 131x100'], null=True, upload_to=apps.organizacion.models.Dependencia.selloPath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), modulos.utiles.clases.varios.FileDimensionValidator(131, 100)], verbose_name='Sello de Firma'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='sello_firma_adicional',
            field=models.ImageField(blank=True, null=True, upload_to=apps.organizacion.models.Dependencia.selloPath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), modulos.utiles.clases.varios.FileDimensionValidator(200, 66)], verbose_name='Sello de Firma Adicional'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='sello_vistobueno',
            field=models.ImageField(blank=True, help_text=['El tamaño debe de ser 200x65'], null=True, upload_to=apps.organizacion.models.Dependencia.selloPath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), modulos.utiles.clases.varios.FileDimensionValidator(200, 65)], verbose_name='Sello de VB'),
        ),
    ]
