# Generated by Django 4.0.5 on 2022-06-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0035_alter_dependencia_sello_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='sello_firmagrc',
            field=models.BooleanField(default=False, verbose_name='Usar sello interno del Firmador'),
        ),
    ]
