# Generated by Django 3.2.6 on 2021-11-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='paracomision',
            field=models.BooleanField(default=False, verbose_name='Para Comisión'),
        ),
    ]
