# Generated by Django 3.2.6 on 2021-11-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_cargo_paracomision'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='alias',
            field=models.CharField(default='', max_length=50, verbose_name='Alias'),
        ),
    ]
