# Generated by Django 3.2.6 on 2021-11-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_persona_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='esprincipal',
            field=models.BooleanField(default=False, verbose_name='Es Principal'),
        ),
    ]
