# Generated by Django 3.2.9 on 2021-12-13 13:57

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0005_cargo_esprincipal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('denominacion', models.CharField(max_length=200)),
                ('nombredecenio', models.CharField(blank=True, max_length=200, null=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Año',
                'verbose_name_plural': 'Años',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
