# Generated by Django 3.2.9 on 2021-12-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='paraunidad',
            field=models.BooleanField(default=True, verbose_name='Para Unidad Organizacional'),
        ),
    ]
