# Generated by Django 3.2.9 on 2021-12-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_cargo_paraunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='personajuridica',
            name='tipo',
            field=models.CharField(choices=[('R', 'RUC'), ('O', 'Otro')], default='R', max_length=1, verbose_name='Tipo'),
        ),
    ]
