# Generated by Django 3.2.9 on 2021-12-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_personajuridica_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ultimocargo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Último Cargo'),
        ),
    ]
