# Generated by Django 3.2.9 on 2022-01-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_alter_personajuridica_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaconfiguracion',
            name='certificadovencimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento de Certificado'),
        ),
    ]
