# Generated by Django 3.2.9 on 2022-01-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_personaconfiguracion_certificadovencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaconfiguracion',
            name='certificadoaviso',
            field=models.DateField(blank=True, null=True, verbose_name='Aviso de Vencimiento de Certificado'),
        ),
    ]
