# Generated by Django 3.2.9 on 2022-02-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_personaconfiguracion_certificadoaviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='esapoyo',
            field=models.BooleanField(default=False, verbose_name='Es Apoyo'),
        ),
    ]
