# Generated by Django 3.2.9 on 2022-03-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0013_cargo_esapoyo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='anio',
            index=models.Index(fields=['numero'], name='inicio_anio_numero_f37a85_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['nombre'], name='inicio_depa_nombre_e05c76_idx'),
        ),
        migrations.AddIndex(
            model_name='pais',
            index=models.Index(fields=['nombre'], name='inicio_pais_nombre_847182_idx'),
        ),
    ]
