# Generated by Django 4.0.3 on 2022-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0015_auto_20220306_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='confirmado',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('tipodocumentoidentidad', 'numero')},
        ),
    ]
