# Generated by Django 4.0.3 on 2022-06-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0016_alter_persona_confirmado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personajuridica',
            unique_together={('tipo', 'ruc')},
        ),
    ]
